import { createSchema } from "../shared";

const userSchema = createSchema({
  provider: String, // The provider with which the user authenticated (facebook, twitter, etc.).
  id: String, // A unique identifier for the user, as generated by the service provider.
  displayName: String, // The name of this user, suitable for display.
  name: {
    familyName: String, // The family name of this user, or "last name" in most Western languages.
    givenName: String, // The given name of this user, or "first name" in most Western languages.
    middleName: String // The middle name of this user.
  },
  emails: [
    {
      value: String, // The actual email address.
      type: { type: String } // The type of email address (home, work, etc.).
    }
  ],
  photos: [
    {
      value: String // The URL of the image.
    }
  ],

  /**
   * Custom properties - Not part of OAuth2 standard
   */
  organizations: [String],
  role: {
    type: Number,
    default: null
  }
});

userSchema.index({
  displayName: "text",
  "name.familyName": "text",
  "name.givenName": "text",
  "name.middleName": "text"
});

export default userSchema;
